### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SHARPvasu** [vsserafim/twotasks-posix-gcc#1]
no FreeRTOS.h is not found 
it showing fatal error 
how to solve it

**Comment by vsserafim** [comment]
> no FreeRTOS.h is not found 
> 
> it showing fatal error 
> 
> how to solve it

Hello there, you may find some usefull information here: https://youtu.be/wZmXPj1YvBg It is in Portuguese, but you can use the automatic translation.
